name: Metrics
on:
  schedule: [{ cron: "0 4 * * *" }]
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🧣 create metrics
        uses: lowlighter/metrics@latest
        with:
          # Gist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          filename: cursus_metrics.svg

          # Configs
          user: 42cursus-youkim
          token: ${{ secrets.GH_TOKEN }}
          config_timezone: Asia/Seoul
          template: classic
          base: header, community, repositories, metadata
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Code
          # plugin_code: yes
          # plugin_code_visibility: public

          # Introduction
          # plugin_introduction: yes
          # plugin_introduction_title: yes

          # Traffic
          # plugin_traffic: yes
