name: Metrics
on:
  schedule: [{ cron: "0 4 * * *" }]
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🧣 create metrics
        uses: lowlighter/metrics@latest
        with:
          # Gist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          filename: cursus_metrics.svg

          # Configs
          user: 42cursus-youkim
          token: ${{ secrets.GH_TOKEN }}
          config_timezone: Asia/Seoul
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Code
          plugin_code: yes
          plugin_code_visibility: public

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 5%
          plugin_languages_ignored: PLSQL, html, css
          plugin_languages_skipped: dotfiles
          commits_authoring: greenscarf005@gmail.com, 42.4.youkim@gmail.com, pig05.kim@gmail.com, youkim@knou.ac.kr

          # Lines
          plugin_lines: yes

          # Traffic
          plugin_traffic: yes
