name: Metrics
on:
  schedule: [{ cron: "0 4 * * *" }]
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🧣 create metrics
        uses: lowlighter/metrics@latest
        with:
          # Gist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          filename: cursus_metrics.svg

          # Configs
          user: 42cursus-youkim
          token: ${{ secrets.GH_TOKEN }}
          config_timezone: Asia/Seoul
          template: classic
          base: header, activity, community, repositories, metadata

          # IsoCalendar
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_activity_ignored: github-actions[bot]

          # Code
          plugin_code: yes
          plugin_code_lines: 12
          plugin_code_load: 100
          plugin_code_visibility: public

          # Followup
          #plugin_followup: yes
          #plugin_followup_sections: repositories

          # Habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_ignored: PLSQL, html, css
          plugin_languages_skipped: dotfiles
          commits_authoring: greenscarf005@gmail.com, 42.4.youkim@gmail.com, pig05.kim@gmail.com, youkim@knou.ac.kr

          # Lines
          plugin_lines: yes

          # Notable
          # plugin_notable: yes
          # plugin_notable_from: organization

          # Traffic
          plugin_traffic: yes

          # Wakatime
          # plugin_wakatime: yes
          # plugin_wakatime_days: 7
          # plugin_wakatime_limit: 5
          # plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          # plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
